project:
  type: website
  render:
    - picross.Rmd

website:
  back-to-top-navigation: true
  page-navigation: true
  title: "Myte_project"
  site-url: https://attoum8643f.github.io/PicrossGame/
  repo-url: https://github.com/attoum8643f/PicrossGame
  repo-actions: [source,issue]
  navbar:
    title: "Picross"
    background: darkgreen
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
