name: Deployment du jeu Picross

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Utilise Windows comme système d'exploitation pour l'exécution
    
    steps:
      # Étape 1 : Récupérer le dépôt GitHub
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Étape 2 : Configuration de R
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      
      # Étape 3 : Exécution du script R pour l'installation des packages
      - name: Installation des packages
        run: |
          Rscript install.R   
      
      # Étape 4 : Déploiement de l'application Shiny sur Shinyapps.io
      - name: Déploiement du jeu Picross
        run: Rscript -e "rsconnect::deployApp(appDir = '.', token = '${{ secrets.SHINYAPPSIO_TOKEN }}')"
